// Validates design/tokens.json (WCAG contrast pairs) and generates:
//   apps/mobile/lib/core/theme/tokens.g.dart
//   design/tokens.css
// Usage: node tools/tokens/build.mjs [--check]   (--check validates only; exits 1 on failure)
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const REPO = resolve(import.meta.dirname, '../..');
const tokens = JSON.parse(await readFile(resolve(REPO, 'design/tokens.json'), 'utf8'));
const checkOnly = process.argv.includes('--check');

const get = (path) => path.split('.').reduce((o, k) => o?.[k], tokens.color);
const channel = (c) => { c /= 255; return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4; };
const luminance = (hex) => {
  const n = parseInt(hex.slice(1), 16);
  return 0.2126 * channel((n >> 16) & 255) + 0.7152 * channel((n >> 8) & 255) + 0.0722 * channel(n & 255);
};
export const contrast = (a, b) => { const [x, y] = [luminance(a), luminance(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };

let failed = 0;
for (const [fg, bg, min] of tokens.contrast.pairs) {
  const ratio = contrast(get(fg), get(bg));
  const ok = ratio >= min;
  if (!ok) failed++;
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${fg.padEnd(24)} on ${bg.padEnd(12)} ${ratio.toFixed(2)} (min ${min})`);
}
if (failed) { console.error(`\n${failed} contrast pair(s) failed`); process.exit(1); }
if (checkOnly) process.exit(0);

// ---------------------------------------------------------------- Dart
const dartColor = (hex) => `Color(0xFF${hex.slice(1).toUpperCase()})`;
const camel = (s) => s.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase());
const colorLines = [];
for (const [group, value] of Object.entries(tokens.color)) {
  if (Array.isArray(value)) {
    colorLines.push(`  static const List<Color> ${group} = [${value.map(dartColor).join(', ')}];`);
    continue;
  }
  for (const [k, v] of Object.entries(value)) {
    if (k.startsWith('$')) continue;
    colorLines.push(`  static const Color ${camel(`${group}_${k}`)} = ${dartColor(v)};`);
  }
}
const fontFamily = (f) => tokens.font[f].family;
const typeLines = Object.entries(tokens.type).map(([name, t]) =>
  `  static const TextStyle ${name} = TextStyle(fontFamily: '${fontFamily(t.font)}', fontSize: ${t.size}, height: ${(t.line / t.size).toFixed(4)}, fontWeight: FontWeight.w${t.weight}, letterSpacing: ${(t.tracking * t.size).toFixed(3)});`);
const spaceLines = Object.entries(tokens.space).map(([k, v]) => `  static const double s${k} = ${v};`);
const radiusLines = Object.entries(tokens.radius).map(([k, v]) => `  static const double ${k} = ${v};`);
const motion = tokens.motion;
const motionLines = [
  ...Object.entries(motion.duration).map(([k, v]) => `  static const Duration ${k} = Duration(milliseconds: ${v});`),
  ...Object.entries(motion.easing).map(([k, v]) => `  static const Cubic ${k}Curve = Cubic(${v.join(', ')});`),
];
const e = tokens.elevation.raised;
const dart = `// GENERATED by tools/tokens/build.mjs from design/tokens.json — do not edit by hand.
// ignore_for_file: constant_identifier_names
import 'package:flutter/animation.dart';
import 'package:flutter/painting.dart';

/// Clean Blue palette. Paper = the white app surface; volt = the brand blue; ink = dark accents (snackbars, photo overlays).
abstract final class ArivoColors {
${colorLines.join('\n')}
}

abstract final class ArivoFonts {
  static const String display = '${fontFamily('display')}';
  static const String ui = '${fontFamily('ui')}';
  static const String mono = '${fontFamily('mono')}';
}

abstract final class ArivoType {
${typeLines.join('\n')}
}

abstract final class ArivoSpace {
${spaceLines.join('\n')}
}

abstract final class ArivoRadius {
${radiusLines.join('\n')}
}

abstract final class ArivoMotion {
${motionLines.join('\n')}
}

abstract final class ArivoElevation {
  static const List<BoxShadow> raised = [
    BoxShadow(color: Color(0x${Math.round(e.opacity * 255).toString(16).padStart(2, '0').toUpperCase()}${e.color.slice(1).toUpperCase()}), offset: Offset(0, ${e.y}), blurRadius: ${e.blur}),
  ];
}

abstract final class ArivoSize {
${Object.entries(tokens.size).map(([k, v]) => `  static const double ${k} = ${v};`).join('\n')}
}
`;

// ---------------------------------------------------------------- CSS
const cssVars = [];
for (const [group, value] of Object.entries(tokens.color)) {
  if (Array.isArray(value)) { value.forEach((v, i) => cssVars.push(`  --${group}-${i + 1}: ${v};`)); continue; }
  for (const [k, v] of Object.entries(value)) if (!k.startsWith('$')) cssVars.push(`  --${group}-${k}: ${v};`);
}
for (const [k, v] of Object.entries(tokens.space)) cssVars.push(`  --space-${k}: ${v}px;`);
for (const [k, v] of Object.entries(tokens.radius)) cssVars.push(`  --radius-${k}: ${v}px;`);
for (const [k, v] of Object.entries(motion.duration)) cssVars.push(`  --dur-${k}: ${v}ms;`);
for (const [k, v] of Object.entries(motion.easing)) cssVars.push(`  --ease-${k}: cubic-bezier(${v.join(', ')});`);
for (const [f, def] of Object.entries(tokens.font)) cssVars.push(`  --font-${f}: '${def.family}', ${def.fallback};`);
const css = `/* GENERATED by tools/tokens/build.mjs from design/tokens.json — do not edit by hand. */
:root {
${cssVars.join('\n')}
}
`;

const dartPath = resolve(REPO, 'apps/mobile/lib/core/theme/tokens.g.dart');
await mkdir(dirname(dartPath), { recursive: true });
await writeFile(dartPath, dart);
await writeFile(resolve(REPO, 'design/tokens.css'), css);
console.log(`\nwrote ${dartPath}\nwrote design/tokens.css`);
