// GENERATED by tools/tokens/build.mjs from design/tokens.json — do not edit by hand.
// ignore_for_file: constant_identifier_names
import 'package:flutter/animation.dart';
import 'package:flutter/painting.dart';

/// Clean Blue palette. Paper = the white app surface; volt = the brand blue; ink = dark accents (snackbars, photo overlays).
abstract final class ArivoColors {
  static const Color ink600 = Color(0xFF3A4A6E);
  static const Color ink700 = Color(0xFF26334F);
  static const Color ink800 = Color(0xFF1B2640);
  static const Color ink900 = Color(0xFF111A2E);
  static const Color ink950 = Color(0xFF0B1220);
  static const Color paper50 = Color(0xFFFFFFFF);
  static const Color paper100 = Color(0xFFFFFFFF);
  static const Color paper200 = Color(0xFFF3F6FB);
  static const Color paper300 = Color(0xFFE4E8F0);
  static const Color textOnPaper = Color(0xFF0F172A);
  static const Color textOnPaperMuted = Color(0xFF64748B);
  static const Color textOnInk = Color(0xFFF8FAFC);
  static const Color textOnInkMuted = Color(0xFFA5B1C8);
  static const Color textOnVolt = Color(0xFFFFFFFF);
  static const Color accentVolt = Color(0xFF1F6BFF);
  static const Color accentSignal = Color(0xFF5B9BFF);
  static const Color accentLantern = Color(0xFFF59E0B);
  static const Color accentEmber = Color(0xFFEF4444);
  static const Color accentOnPaperVolt = Color(0xFF1A5FE6);
  static const Color accentOnPaperSignal = Color(0xFF1A5FE6);
  static const Color accentOnPaperLantern = Color(0xFFB45309);
  static const Color accentOnPaperEmber = Color(0xFFDC2626);
  static const List<Color> route = [Color(0xFF1F6BFF), Color(0xFFF97316), Color(0xFF10B981), Color(0xFFEC4899), Color(0xFF8B5CF6), Color(0xFF06B6D4), Color(0xFFF59E0B), Color(0xFF475569)];
  static const List<Color> crew = [Color(0xFF1F6BFF), Color(0xFFF59E0B), Color(0xFFEC4899), Color(0xFF8B5CF6), Color(0xFF10B981), Color(0xFF06B6D4)];
  static const Color provenanceLive = Color(0xFF1F6BFF);
  static const Color provenanceEstimate = Color(0xFFF59E0B);
  static const Color provenanceYou = Color(0xFF10B981);
}

abstract final class ArivoFonts {
  static const String display = 'Plus Jakarta Sans';
  static const String ui = 'Plus Jakarta Sans';
  static const String mono = 'Plus Jakarta Sans';
}

abstract final class ArivoType {
  static const TextStyle displayXL = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 34, height: 1.1765, fontWeight: FontWeight.w700, letterSpacing: -0.680);
  static const TextStyle displayL = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 28, height: 1.2143, fontWeight: FontWeight.w700, letterSpacing: -0.420);
  static const TextStyle displayM = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 24, height: 1.2500, fontWeight: FontWeight.w700, letterSpacing: -0.240);
  static const TextStyle titleL = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 20, height: 1.3000, fontWeight: FontWeight.w700, letterSpacing: -0.200);
  static const TextStyle titleM = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 17, height: 1.2941, fontWeight: FontWeight.w600, letterSpacing: -0.085);
  static const TextStyle bodyL = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 16, height: 1.5000, fontWeight: FontWeight.w400, letterSpacing: 0.000);
  static const TextStyle bodyM = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 14, height: 1.4286, fontWeight: FontWeight.w400, letterSpacing: 0.000);
  static const TextStyle label = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 13, height: 1.2308, fontWeight: FontWeight.w600, letterSpacing: 0.000);
  static const TextStyle caption = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 12, height: 1.3333, fontWeight: FontWeight.w500, letterSpacing: 0.000);
  static const TextStyle monoL = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 22, height: 1.2727, fontWeight: FontWeight.w700, letterSpacing: -0.220);
  static const TextStyle monoM = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 15, height: 1.3333, fontWeight: FontWeight.w600, letterSpacing: 0.000);
  static const TextStyle monoS = TextStyle(fontFamily: 'Plus Jakarta Sans', fontSize: 12, height: 1.3333, fontWeight: FontWeight.w600, letterSpacing: 0.240);
}

abstract final class ArivoSpace {
  static const double s0 = 0;
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
}

abstract final class ArivoRadius {
  static const double xs = 8;
  static const double s = 12;
  static const double m = 14;
  static const double l = 24;
  static const double pill = 999;
}

abstract final class ArivoMotion {
  static const Duration fast = Duration(milliseconds: 140);
  static const Duration base = Duration(milliseconds: 220);
  static const Duration slow = Duration(milliseconds: 420);
  static const Duration route = Duration(milliseconds: 700);
  static const Cubic standardCurve = Cubic(0.2, 0, 0, 1);
  static const Cubic emphasizedCurve = Cubic(0.3, 0, 0, 1);
  static const Cubic exitCurve = Cubic(0.4, 0, 1, 1);
}

abstract final class ArivoElevation {
  static const List<BoxShadow> raised = [
    BoxShadow(color: Color(0x120F172A), offset: Offset(0, 4), blurRadius: 16),
  ];
}

abstract final class ArivoSize {
  static const double touchMin = 48;
  static const double fab = 60;
  static const double sheetHandle = 36;
}
